toolbx-images/images

COPYING
Since all the contributions to the original repo was with Apache 2.0, we
retain the same license to this repository.
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> Add license

.github/workflows/archlinux.yaml, .github/workflows/centos.yaml, .github/workflows/debian.yaml, .github/workflows/rhel.yaml, .github/workflows/ubuntu.yaml, README.md
Use shared names for environment variables to unify most of the workflow definition for all distributions.
Remove obsolete GitHub Action notes from README as we apparently have unlimited action minutes for free repositories.
=> github/workflow: Run on PRs and unify definition

.github/workflows/archlinux-pr.yaml, .github/workflows/centos-pr.yaml, .github/workflows/centos.yaml, .github/workflows/debian-pr.yaml, .github/workflows/debian.yaml, .github/workflows/rhel-pr.yaml, .github/workflows/rhel.yaml, .github/workflows/ubuntu-pr.yaml, .github/workflows/ubuntu.yaml
This simplifies the logic and will enable concurent PR testing while keeping push & scheduled workflows running sequentially.
=> workflows: Split PRs & push/schedule jobs

.github/workflows/archlinux-pr.yaml, .github/workflows/archlinux.yaml, .github/workflows/centos-pr.yaml, .github/workflows/centos.yaml, .github/workflows/debian-pr.yaml, .github/workflows/debian.yaml, .github/workflows/rhel-pr.yaml, .github/workflows/rhel.yaml, .github/workflows/ubuntu-pr.yaml, .github/workflows/ubuntu.yaml
Make sure to not re-use cached layers to always fully update the image every time we rebuilt it.
See: https://github.com/toolbx-images/images/issues/5
=> github/workflow: Do not use cache to always update

centos/stream8/extra-packages, centos/stream9/extra-packages
Currently causing dependency issue when enabling EPEL.
=> centos: Temporarily remove gnupg2-smime

centos/stream9/extra-packages
Partially revert "centos: Temporarily remove gnupg2-smime"
This partially reverts commit 685bb34b06328e832452ff8425cb514576ed95c4.
=> centos/stream9: Re-add gnupg2-smime

.github/workflows/centos.yaml, .github/workflows/debian.yaml, .github/workflows/opensuse.yaml, .github/workflows/rhel.yaml, .github/workflows/rockylinux.yaml, .github/workflows/ubuntu.yaml
The workflows were wrongly using the 'no-cache' option only for the "latest" build and push action and were not correctly rebuilding everything.
Let's use this option for all builds while not using it in the latest tag push as we don't need to rebuild something we've just built.
=> github/workflow: Use the cached image for pushing the latest tag

ubuntu/20.04/Containerfile, ubuntu/20.04/extra-packages, ubuntu/22.04/Containerfile, ubuntu/22.04/extra-packages
This allows [toolbox-vscode](https://github.com/owtaylor/toolbox-vscode) to work with the Ubuntu Containers. The package was introduced in version 20.04, that's why there is no changes on 16.04 and 18.04.
=> Ubuntu: Added flatpak-xdg-utils to extra-packages and linked flatpak-spawn to /usr/bin

alpine/3.16/Containerfile, alpine/3.17/Containerfile
/media has a different meaning / setup depending of the distribution. Remove it and toolbox will re-create as neeed to match the host distribution setup.
Fixes: https://github.com/toolbx-images/images/issues/65
=> alpine: Remove /media and let toolbox handle it

debian/10/Containerfile, debian/10/toolbox-flatpak-xdg-utils.sh, debian/11/Containerfile, debian/11/toolbox-flatpak-xdg-utils.sh, debian/testing/Containerfile, debian/testing/toolbox-flatpak-xdg-utils.sh, debian/unstable/Containerfile, debian/unstable/toolbox-flatpak-xdg-utils.sh
* Prevent questions when installing packages during the build
* Make flatpak-xdg-utils usable inside the toolbox
=> Contribute back changes from Apertis images

ubuntu/16.04/extra-packages, ubuntu/18.04/extra-packages, ubuntu/20.04/extra-packages, ubuntu/22.04/extra-packages, ubuntu/22.10/extra-packages
Fixes: https://github.com/toolbx-images/images/issues/73
=> ubuntu: Add libcap2-bin for capsh

ubuntu/16.04/extra-packages, ubuntu/18.04/Containerfile, ubuntu/18.04/extra-packages, ubuntu/20.04/extra-packages, ubuntu/22.04/extra-packages, ubuntu/22.10/extra-packages
It appears they were removed for some reason.
Bring them back as well as execution of `unminimize`.
It is now again aligned with other ubuntu releases.
Also, revert adding `libcap2-bin` to the package list.
Fixes: #72, #73
=> Fix Ubuntu 18.04 missing core desktop metapackages

.github/workflows/alpine-pr.yaml, .github/workflows/alpine.yaml, README.md
Alpine 3.19 images are now on Docker Hub.
=> alpine: enable 3.19 as latest version

.github/workflows/almalinux.yaml, .github/workflows/alpine.yaml, .github/workflows/amazonlinux.yaml, .github/workflows/archlinux.yaml, .github/workflows/centos.yaml, .github/workflows/debian.yaml, .github/workflows/fedora.yaml, .github/workflows/opensuse.yaml, .github/workflows/rhel.yaml, .github/workflows/rockylinux.yaml, .github/workflows/ubuntu.yaml
We should update the ubuntu repos before installing `qemu-user-static` otherwise we can sometimes be hit with 404 errors.
=> workflows: update ubuntu repositories beforehand (all)

opensuse/tumbleweed/Containerfile
It looks like xargs has been removed from the base image of tumbleweed. Let's make sure it's installed before using it.
=> opensuse/tumbleweed: Install xargs first

centos/stream10/Containerfile, centos/stream9/Containerfile
centos: Enable EPEL for Stream 10
---
centos: Use recommended package for EPEL 9
See: https://docs.fedoraproject.org/en-US/epel/getting-started/#_el9
=> centos: Enable EPEL for Stream 10

.github/workflows/debian.yaml
Debian container image builds are currently failing on Ubuntu 24.04 runners for Debian < 12.
=> github/workflows: Keep Debian builds on ubuntu-22.04

.github/workflows/almalinux.yaml, .github/workflows/alpine.yaml, .github/workflows/amazonlinux.yaml, .github/workflows/centos.yaml, .github/workflows/debian.yaml, .github/workflows/rockylinux.yaml
Do not fail all builds if one version fails. This should keep images updated until the one with the failure is fixed.
See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
=> github/workflows: Disable fail-fast

debian/10/Containerfile, debian/11/Containerfile, debian/12/Containerfile, debian/testing/Containerfile, debian/unstable/Containerfile
This is set by the `ARG` directive just above this command.
=> Remove DEBIAN_FRONTEND=noninteractive from apt-get invocation

.github/workflows/debian.yaml, README.md
My bad: I forgot to add the Debian 13 image to the pipeline. :-)
=> ci: add debian 13 to the build pipeline
